{{- if .Values.Secret }}

{{- $release_namespace := .Release.namespace }}
{{- $labels := include "demo.labels" . }}

{{- range $secret := .Values.Secret }}
{{- with $secret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $release_namespace }}
  
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

type: {{ .type }}

{{- with .data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- with .stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
