{{- if .Values.ConfigMap }}

{{- $release_namespace := .Release.namespace }}
{{- $labels := include "<CHARTNAME>.labels" . }}

{{- with .Values.ConfigMap }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $release_namespace }}
  
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

data:
  {{- with .data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

{{- with .binaryData }}
binaryData:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- end }}
{{- end }}